const express = require('express'); // Load express to serve the website
const path = require('path'); // Load path to find the files to serve
const fs = require('fs'); // Load fs to write the enviorment variables into a file
const port = process.env.PORT || 3000; // set the default port back to 3000 (8080 causes conflicts in nanobox, do not use)
// set up the express application
const app = express();
// write out the relevent client side enviroment variables to env.js

app.configure('development', () => {
    app.use(express.errorHandler({ dumpExceptions: true, showStack: true }));
})

app.configure('production', () => {
    app.use(express.errorHandler())
})

fs.writeFileSync(
  __dirname + '/config/env.js',
  'var config = {REACT_APP_API_URL: "' + process.env.REACT_APP_API_URL+ '"};'
);
// serve the files generated by `react-scripts build`
app.use(express.static(__dirname + '/build'));
// serve the env.js file generated above
app.use(express.static(__dirname + '/config'));
// for all other paths return the index.html file from the build (react application handles all other routes)
app.get('*', function (request, response) {
  response.sendFile(path.resolve(__dirname, 'build/index.html'));
});
// set the app to start on port 3000 (or PORT)
app.listen(port);
